2017-12-23 14:58:18,587 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNTE0MDU5Mzk5LjU2MDM4Mn0.gFIx0gOoc4dyIjJ36pI-tpsjoLFSihaqVoKqUgsBsDg [GET] [in /Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mfabian1/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mfabian1/Desktop/microblog/app/routes.py", line 152, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2017-12-23 14:59:02,242 INFO: Microblog startup [in /Users/mfabian1/Desktop/microblog/app/__init__.py:42]
